### ISSUE TITLE
`NullPointerException` when `stopService()` is called on the bubble intent

### ISSUE THREAD

**Issue by moazelsawaf** [TorryDo/Floating-Bubble-View#18]
When I try to stop the service I get the following exception while I am not overriding `setupExpandableView()` and not using anything related to `ExpandableView` at all.

```
E/<> BubbleService: java.lang.NullPointerException
        at com.torrydo.floatingbubbleview.FloatingBubbleServiceConfig.tryRemoveExpandableView(FloatingBubbleServiceConfig.kt:99)
        at com.torrydo.floatingbubbleview.FloatingBubbleServiceConfig.tryRemoveAllView(FloatingBubbleServiceConfig.kt:92)
        at com.torrydo.floatingbubbleview.FloatingBubbleServiceConfig.onDestroy(FloatingBubbleServiceConfig.kt:19)
        at com.torrydo.floatingbubbleview.FloatingBubbleService.onDestroy(FloatingBubbleService.kt:47)
        at android.app.ActivityThread.handleStopService(ActivityThread.java:4825)
        at android.app.ActivityThread.access$2200(ActivityThread.java:276)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2173)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8261)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
D/DecorView[]: onWindowFocusChanged hasWindowFocus true
W/System: A resource failed to call close. 
```

**Comment by TorryDo** [comment]
After investigating the issue, I have found that the error message is actually just a print statement that I forgot to remove. I apologize for any confusion this may have caused.

Please know that this print statement does not affect the functionality of the library and can be safely ignored. However, I will remove it in the next release to avoid any confusion in the future.

If this response does not satisfy you, please don't hesitate to re-open the issue and let me know. I am always happy to help and answer any questions you may have.

Thank you for your interest in this library

```java
Log.e("<> $tag", e.stackTraceToString()) // the culprit
```

**Comment by moazelsawaf** [comment]
Thank you so much 🙏🏻

I will comment it out in a fork until you release a new version.

I also wanted to tell you that I am currently building a Flutter package that depends on this dependency and I will reference this work in the README Insh'Allah 🙏🏻💙

**Comment by TorryDo** [comment]
Thank you for your kind words! It's always great to hear that the library is being used and incorporated into other projects.

I appreciate your plan to reference this work in your README. If you have any questions or need help with anything, please don't hesitate to reach out to me. I'm excited to see how it will be used in your project.

Best regards

**Comment by TorryDo** [comment]
Thank you for your kind words! It's always great to hear that the library is being used and incorporated into other projects.

I appreciate your plan to reference this work in your README. If you have any questions or need assistance with the library, don't hesitate to ask. I'm excited to see how it will be used in your project.

Best regards
