### ISSUE TITLE
can not implement 

### ISSUE THREAD

**Issue by fahimfahadleon** [TorryDo/Floating-Bubble-View#21]
java.lang.NullPointerException
                                       	at com.torrydo.floatingbubbleview.FloatingBubbleServiceConfig.tryRemoveExpandableView(FloatingBubbleServiceConfig.kt:89)
                                       	at com.torrydo.floatingbubbleview.FloatingBubbleServiceConfig.tryRemoveAllView(FloatingBubbleServiceConfig.kt:82)
                                       	at com.torrydo.floatingbubbleview.FloatingBubbleServiceConfig.onDestroy(FloatingBubbleServiceConfig.kt:13)
                                       	at com.torrydo.floatingbubbleview.FloatingBubbleService.onDestroy(FloatingBubbleService.kt:61)
                                       	at android.app.ActivityThread.handleStopService(ActivityThread.java:4789)
                                       	at android.app.ActivityThread.access$2200(ActivityThread.java:264)
                                       	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2145)
                                       	at android.os.Handler.dispatchMessage(Handler.java:106)
                                       	at android.os.Looper.loopOnce(Looper.java:210)
                                       	at android.os.Looper.loop(Looper.java:299)
                                       	at android.app.ActivityThread.main(ActivityThread.java:8105)
                                       	at java.lang.reflect.Method.invoke(Native Method)
                                       	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                       	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
<> ChatBubbleService                E  java.lang.NullPointerException
                                       	at com.torrydo.floatingbubbleview.FloatingBubbleServiceConfig.tryRemoveBubbles(FloatingBubbleServiceConfig.kt:101)
                                       	at com.torrydo.floatingbubbleview.FloatingBubbleServiceConfig.tryRemoveAllView(FloatingBubbleServiceConfig.kt:83)
                                       	at com.torrydo.floatingbubbleview.FloatingBubbleServiceConfig.onDestroy(FloatingBubbleServiceConfig.kt:13)
                                       	at com.torrydo.floatingbubbleview.FloatingBubbleService.onDestroy(FloatingBubbleService.kt:61)
                                       	at android.app.ActivityThread.handleStopService(ActivityThread.java:4789)
                                       	at android.app.ActivityThread.access$2200(ActivityThread.java:264)
                                       	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2145)
                                       	at android.os.Handler.dispatchMessage(Handler.java:106)
                                       	at android.os.Looper.loopOnce(Looper.java:210)
                                       	at android.os.Looper.loop(Looper.java:299)
                                       	at android.app.ActivityThread.main(ActivityThread.java:8105)
                                       	at java.lang.reflect.Method.invoke(Native Method)
                                       	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                       	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by fukemy** [comment]
It's your error not lib error, please take some research / try to find problem first intead of posting the question
