### ISSUE TITLE
complex expandable view

### ISSUE THREAD

**Issue by fahimfahadleon** [TorryDo/Floating-Bubble-View#22]
Is there an instruction for implementing complex layout such as a layout containing a recyclerview some textviews some circlerImageView some imageviews and lottieAnimationView? I am getting error while infleting
  

`FATAL EXCEPTION: main
                                       Process: com.horoftech.mc, PID: 3708
                                       java.lang.RuntimeException: Unable to start service com.horoftech.mc.Services.ChatBubbleService@46b9692 with Intent { cmp=com.horoftech.mc/.Services.ChatBubbleService }: android.view.InflateException: Binary XML file line #57 in com.horoftech.mc:layout/viewprofilepicture: Binary XML file line #57 in com.horoftech.mc:layout/viewprofilepicture: Error inflating class android.widget.TextView
                                       	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4777)
                                       	at android.app.ActivityThread.access$2100(ActivityThread.java:264)
                                       	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2140)
                                       	at android.os.Handler.dispatchMessage(Handler.java:106)
                                       	at android.os.Looper.loopOnce(Looper.java:210)
                                       	at android.os.Looper.loop(Looper.java:299)
                                       	at android.app.ActivityThread.main(ActivityThread.java:8105)
                                       	at java.lang.reflect.Method.invoke(Native Method)
                                       	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                       	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
                                       Caused by: android.view.InflateException: Binary XML file line #57 in com.horoftech.mc:layout/viewprofilepicture: Binary XML file line #57 in com.horoftech.mc:layout/viewprofilepicture: Error inflating class android.widget.TextView
                                       Caused by: android.view.InflateException: Binary XML file line #57 in com.horoftech.mc:layout/viewprofilepicture: Error inflating class android.widget.TextView
                                       Caused by: java.lang.reflect.InvocationTargetException
                                       	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                       	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                       	at android.view.LayoutInflater.createView(LayoutInflater.java:881)
                                       	at android.view.LayoutInflater.createView(LayoutInflater.java:803)
                                       	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
                                       	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:957)
                                       	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:977)
                                       	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1031)
                                       	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:988)
                                       	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1150)
                                       	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1111)
                                       	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1153)
                                       	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1111)
                                       	at android.view.LayoutInflater.inflate(LayoutInflater.java:709)
                                       	at android.view.LayoutInflater.inflate(LayoutInflater.java:547)
                                       	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
                                       	at com.horoftech.mc.Services.ChatBubbleService.setupExpandableView(ChatBubbleService.java:75)
                                       	at com.torrydo.floatingbubbleview.FloatingBubbleServiceConfig.setupViewAppearance(FloatingBubbleServiceConfig.kt:30)
                                       	at com.torrydo.floatingbubbleview.FloatingBubbleService.onStartCommand(FloatingBubbleService.kt:49)
                                       	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4759)
                                       	at android.app.ActivityThread.access$2100(ActivityThread.java:264)
                                       	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2140)
                                       	at android.os.Handler.dispatchMessage(Handler.java:106)
                                       	at android.os.Looper.loopOnce(Looper.java:210)
                                       	at android.os.Looper.loop(Looper.java:299)
                                       	at android.app.ActivityThread.main(ActivityThread.java:8105)
                                       	at java.lang.reflect.Method.invoke(Native Method)
                                       	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                       	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
                                       Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 35: TypedValue{t=0x2/d=0x7f0303fd a=-1}
                                       	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1001)
                                       	at android.content.res.TypedArray.getDrawable(TypedArray.java:985)
                                       	at android.view.View.<init>(View.java:6169)
                                       	at android.widget.TextView.<init>(TextView.java:1035)
AndroidRuntime                      E  	at android.widget.TextView.<init>(TextView.java:1029)
                                       	at android.widget.TextView.<init>(TextView.java:1025)
                                       	... 29 more`

nothing much implemented in the override method 
`   @Nullable
    @Override
    public ExpandableView.Builder setupExpandableView(@NonNull ExpandableView.Action action) {

        LayoutInflater inflater = (LayoutInflater) getSystemService(LAYOUT_INFLATER_SERVICE);
        View layout = inflater.inflate(R.layout.viewprofilepicture, null);

        layout.findViewById(R.id.profilepicture).setOnClickListener(v -> {
            Toast.makeText(this, "hello from card view from java", Toast.LENGTH_SHORT).show();
            action.popToBubble();
        });

        return new ExpandableView.Builder(this)
                .expandableView(layout)
                .dimAmount(0.8f)
                .addExpandableViewListener(new ExpandableView.Listener() {
                    @Override
                    public void onOpenExpandableView() {}

                    @Override
                    public void onCloseExpandableView() {}
                })
                .expandableViewStyle(null);
    }`

**Comment by TorryDo** [comment]
Hi @fahimfahadleon 👋! 

It sounds like you're facing some challenges with building a complex view. I built a complex view before and didn't find any issue with this approach. You can see here: https://youtu.be/dG0OEL_YBG0?t=255 . It's quite a complex view with nested RecyclerViews, LottieAnimations, ...

From my experience, I don't think the issue comes from the library itself. It's possible that there could be something else going on, such as issues with the data being used or the layout being set up incorrectly. Without more information, it's hard to say for sure.

However, I'm more than happy to help you troubleshoot this issue. Can you provide more information about your case? Perhaps we can work together to find a solution that works for you. 🍀☘

**Comment by fahimfahadleon** [comment]
the problem was not within the library i apologies. It was due to theme. i didn't set theme to my layout. btw thanks for the youtube tutorial.
